# Generated by Django 5.0.6 on 2024-07-16 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Gender', models.CharField(max_length=12)),
                ('Phone_Number', models.CharField(max_length=11)),
                ('DOB', models.CharField(max_length=50)),
                ('SelectMembershipPlan', models.CharField(max_length=200)),
                ('SelectTrainer', models.CharField(max_length=20)),
                ('Reference', models.CharField(max_length=50)),
                ('Address', models.TextField()),
                ('Payment_Status', models.CharField(blank=True, max_length=50, null=True)),
                ('Price', models.IntegerField(blank=True, max_length=50, null=True)),
                ('DueDate', models.DateField(blank=True, null=True)),
                ('TimeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Plan', models.CharField(max_length=150)),
                ('Price', models.IntegerField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Gender', models.CharField(max_length=10)),
                ('Phone', models.CharField(max_length=11)),
                ('Salary', models.IntegerField(max_length=25)),
                ('TimeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
