# Generated by Django 5.0.6 on 2024-07-17 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authapp', '0003_alter_enrollment_price_alter_membershipplan_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='DueDate',
            new_name='Due_Date',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='Fullname',
            new_name='Full_name',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='SelectMembershipPlan',
            new_name='Select_MembershipPlan',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='SelectTrainer',
            new_name='Select_Trainer',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='Gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='Phone_Number',
            new_name='phone_Number',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='Reference',
            new_name='reference',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='TimeStamp',
            new_name='timeStamp',
        ),
    ]
