# Generated by Django 5.0.6 on 2024-07-18 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authapp', '0004_rename_duedate_enrollment_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='User_Name',
            field=models.CharField(default=False, max_length=20),
            preserve_default=False,
        ),
    ]
