# Generated by Django 5.0.6 on 2024-07-18 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authapp', '0005_enrollment_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendenceSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Name', models.CharField(max_length=20)),
                ('Login_Time', models.CharField(max_length=50)),
                ('Logout_Time', models.CharField(max_length=50)),
                ('Workout_Type', models.CharField(max_length=50)),
                ('Trained_By', models.CharField(max_length=50)),
            ],
        ),
    ]
